name: plataforma-reserva
version: '3.8' 
services:
  pg:
    image: bitnami/postgresql:13.16.0
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: teste
      POSTGRES_PASSWORD: teste
      POSTGRES_DB: reserva
      
